version: '3'
services:
  backend:
    container_name: backend_kruse
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '20093:5000'
    environment:
      - PORT=5000
      - CONNECTION_URL=mongodb://localhost:20092/database_kruse
    networks:
      - Myths&Forges

  frontend:
    container_name: frontend_kruse
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '20091:3000'
    networks:
      - Myths&Forges

  mongo:
    container_name: database_kruse
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 20092:27017
    networks:
      - Myths&Forges

networks:
  Myths&Forges:
    driver: bridge
